// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace library_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906113736_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyProject.Data.Book", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gatunek")
                        .HasColumnType("text");

                    b.Property<string>("tytul")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            id = 1,
                            autor = "J.R.R. Tolkien",
                            gatunek = "fantasy",
                            tytul = "The Hobbit"
                        },
                        new
                        {
                            id = 2,
                            autor = "J.R.R. Tolkien",
                            gatunek = "fantasy",
                            tytul = "The Fellowship of the Ring"
                        },
                        new
                        {
                            id = 3,
                            autor = "J.K. Rowling",
                            gatunek = "fantasy",
                            tytul = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            id = 4,
                            autor = "Frank Herbert",
                            gatunek = "science fiction",
                            tytul = "Dune"
                        },
                        new
                        {
                            id = 5,
                            autor = "Isaac Asimov",
                            gatunek = "science fiction",
                            tytul = "Foundation"
                        },
                        new
                        {
                            id = 6,
                            autor = "William Gibson",
                            gatunek = "science fiction",
                            tytul = "Neuromancer"
                        },
                        new
                        {
                            id = 7,
                            autor = "Stephen King",
                            gatunek = "horror",
                            tytul = "It"
                        },
                        new
                        {
                            id = 8,
                            autor = "Stephen King",
                            gatunek = "horror",
                            tytul = "The Shining"
                        },
                        new
                        {
                            id = 9,
                            autor = "Bram Stoker",
                            gatunek = "horror",
                            tytul = "Dracula"
                        },
                        new
                        {
                            id = 10,
                            autor = "Jane Austen",
                            gatunek = "romance",
                            tytul = "Pride and Prejudice"
                        },
                        new
                        {
                            id = 11,
                            autor = "Nicholas Sparks",
                            gatunek = "romance",
                            tytul = "The Notebook"
                        },
                        new
                        {
                            id = 12,
                            autor = "Jojo Moyes",
                            gatunek = "romance",
                            tytul = "Me Before You"
                        },
                        new
                        {
                            id = 13,
                            autor = "Robert Louis Stevenson",
                            gatunek = "adventure",
                            tytul = "Treasure Island"
                        },
                        new
                        {
                            id = 14,
                            autor = "Alexandre Dumas",
                            gatunek = "adventure",
                            tytul = "The Three Musketeers"
                        },
                        new
                        {
                            id = 15,
                            autor = "Jules Verne",
                            gatunek = "adventure",
                            tytul = "Around the World in Eighty Days"
                        },
                        new
                        {
                            id = 16,
                            autor = "Walter Isaacson",
                            gatunek = "biography",
                            tytul = "Steve Jobs"
                        },
                        new
                        {
                            id = 17,
                            autor = "Walter Isaacson",
                            gatunek = "biography",
                            tytul = "Einstein: His Life and Universe"
                        },
                        new
                        {
                            id = 18,
                            autor = "Nelson Mandela",
                            gatunek = "biography",
                            tytul = "Long Walk to Freedom"
                        });
                });

            modelBuilder.Entity("MyProject.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "science fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "horror"
                        },
                        new
                        {
                            Id = 4,
                            Name = "romance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "adventure"
                        },
                        new
                        {
                            Id = 6,
                            Name = "biography"
                        });
                });

            modelBuilder.Entity("MyProject.Data.LibraryUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
